









version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_CLOUD_NAME_CLOUDINARY=dqe9raf7i
      - REACT_APP_STRIPE_PUBLIC_KEY=pk_test_51Pb4oGRsMV59PoCGCsXWYzPaqjBWqtERR8OVf6KZW5bMglb32WeJ37axvbocx9A3eM3P66OqQqnBQ8Le3py0Vba500SW7BthLt
      - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb+srv://schinni9999:chinni9999@cluster2.rffpqrc.mongodb.net/MERN-Ecommerce?retryWrites=true&w=majority&appName=Cluster2
      - TOKEN_SECRET_KEY=ASDFGHJKLQWERTYUIOZXCVBNMNWERTYUIOSDFGHJKSDFGHJ
      - FRONTEND_URL=http://localhost:3000
      - STRIPE_SECRET_KEY=sk_test_51Pb4oGRsMV59PoCGfeMgOIBAoJgSqzQX5HRoQSc7IaICJt43r8IueISJkanj1BjAso2DkpmeAMLOFSCEXpm4NTAD00ckSAO1gM
      - STRIPE_ENDPOINT_WEBHOOK_SECRET_KEY=whsec_7211366d450f085c43f8fa79923f7b838bff2c1eebd171a06846b94339dc9927
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/tatah/mongo-backup:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge






















































































































































































































































































































































































































































































































































































































































































































































































































































version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_CLOUD_NAME_CLOUDINARY=dqe9raf7i
      - REACT_APP_STRIPE_PUBLIC_KEY=pk_test_51Pb4oGRsMV59PoCGCsXWYzPaqjBWqtERR8OVf6KZW5bMglb32WeJ37axvbocx9A3eM3P66OqQqnBQ8Le3py0Vba500SW7BthLt
      - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb+srv://schinni9999:chinni9999@cluster2.rffpqrc.mongodb.net/MERN-Ecommerce?retryWrites=true&w=majority&appName=Cluster2
      - TOKEN_SECRET_KEY=ASDFGHJKLQWERTYUIOZXCVBNMNWERTYUIOSDFGHJKSDFGHJ
      - FRONTEND_URL=http://localhost:3000
      - STRIPE_SECRET_KEY=sk_test_51Pb4oGRsMV59PoCGfeMgOIBAoJgSqzQX5HRoQSc7IaICJt43r8IueISJkanj1BjAso2DkpmeAMLOFSCEXpm4NTAD00ckSAO1gM
      - STRIPE_ENDPOINT_WEBHOOK_SECRET_KEY=whsec_7211366d450f085c43f8fa79923f7b838bff2c1eebd171a06846b94339dc9927
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - /home/tatah/mongo-backup:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
